<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KeysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('keys')->truncate();

        DB::table("keys")->insert(
            [
              [ 'name'=>'A0',
                'freq'=>27.5,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A#0',
                'freq'=>29.135,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B0',
                'freq'=>30.868,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C1',
                'freq'=>32.703,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#1',
                'freq'=>34.648,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D1',
                'freq'=>36.708,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#1',
                'freq'=>38.891,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E1',
                'freq'=>41.203,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F1',
                'freq'=>43.654,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#1',
                'freq'=>46.249,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G1',
                'freq'=>48.999,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G#1',
                'freq'=>51.913,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A1',
                'freq'=>55,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              
              [ 'name'=>'A#1',
                'freq'=>58.270,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B1',
                'freq'=>61.735,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C2',
                'freq'=>65.406,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#2',
                'freq'=>69.296,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D2',
                'freq'=>73.416,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#2',
                'freq'=>77.782,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E2',
                'freq'=>82.407,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F2',
                'freq'=>87.307,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#2',
                'freq'=>92.499,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G2',
                'freq'=>97.999,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G#2',
                'freq'=>103.826,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A2',
                'freq'=>110.000,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A#2',
                'freq'=>116.541,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B2',
                'freq'=>123.471,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C3',
                'freq'=>130.813,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#3',
                'freq'=>138.591,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D3',
                'freq'=>146.832,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#3',
                'freq'=>155.563,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E3',
                'freq'=>164.814,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F3',
                'freq'=>174.614,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#3',
                'freq'=>184.997,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G3',
                'freq'=>195.998,
                'created_at'=>now(),
                'updated_at'=>now(),
                ],
              [ 'name'=>'G#3',
                'freq'=>207.652,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A3',
                'freq'=>220,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A#3',
                'freq'=>233.082,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B3',
                'freq'=>246.942,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C4',
                'freq'=>261.626,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#4',
                'freq'=>277.183,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D4',
                'freq'=>293.665,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#4',
                'freq'=>311.127,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E4',
                'freq'=>329.628,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F4',
                'freq'=>349.228,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#4',
                'freq'=>369.994,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G4',
                'freq'=>391.995,
                'created_at'=>now(),
                'updated_at'=>now(),
                ],
              [ 'name'=>'G#4',
                'freq'=>415.305,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A4',
                'freq'=>440.000,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A#4',
                'freq'=>466.164,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B4',
                'freq'=>493.883,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C5',
                'freq'=>523.251,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#5',
                'freq'=>554.365,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D5',
                'freq'=>587.330,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#5',
                'freq'=>622.254,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E5',
                'freq'=>659.255,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F5',
                'freq'=>698.456,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#5',
                'freq'=>739.989,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G5',
                'freq'=>783.991,
                'created_at'=>now(),
                'updated_at'=>now(),
                ],
              [ 'name'=>'G#5',
                'freq'=>830.609,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A5',
                'freq'=>880,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'A#5',
                'freq'=>932.328,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'B5',
                'freq'=>987.767,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C6',
                'freq'=>1046.502,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'C#6',
                'freq'=>1108.731,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D6',
                'freq'=>1174.659,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'D#6',
                'freq'=>1244.508,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'E6',
                'freq'=>1318.510,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F6',
                'freq'=>1396.913,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'F#6',
                'freq'=>1479.978,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
              [ 'name'=>'G6',
                'freq'=>1567.982,
                'created_at'=>now(),
                'updated_at'=>now(),
                ],
              [ 'name'=>'G#6',
                'freq'=>1661.219,
                'created_at'=>now(),
                'updated_at'=>now(),
              ],
            //   [ 'name'=>'A',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'A#',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'B',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'C',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'C#',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'D',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'D#',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'E',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'F',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'F#',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //   [ 'name'=>'G',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //     ],
            //   [ 'name'=>'G#',
            //     'freq'=>,
            //     'created_at'=>now(),
            //     'updated_at'=>now(),
            //   ],
            //  
           
              
              
              ]
            );

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
